# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update Terraform providers and modules
  - package-ecosystem: "terraform"
    directory: "/" # Location of your main Terraform configuration files
    schedule:
      interval: "weekly"

  # Update Python dependencies (if Ansible dependencies are managed with a requirements.txt)
  - package-ecosystem: "pip"
    directory: "/ansible" # Adjust this if you have requirements.txt elsewhere
    schedule:
      interval: "weekly"

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

