name: "Configure Nginx Webservers in Ubuntu via Ansible"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    ## in Case push to main by codeowners
    paths:
    - "ansible/**"
    - ".github/workflows/set-up-ubuntu-nginx-webserver.yaml"
    - ".github/workflows/ansible-set-up.yaml"

  pull_request:
    paths:
    - "ansible/**"
    - ".github/workflows/set-up-ubuntu-nginx-webserver.yaml"
    - ".github/workflows/ansible-set-up.yaml"

concurrency:
  group: ansible-webservers

jobs:
  webserversConfig:
    name: Configure Nginx webservers
    uses: ./.github/workflows/ansible-set-up.yaml
    with:
      playbook: set-up-ubuntu-nginx-webserver.yaml
      terraform-output-directory: terraform/linux-webserver-with-loadbalancer
      nsg-ssh-port: 8822
    secrets:
      ssh-private-key: ${{ secrets.PASSWORDLESS_SSH_PRIVATE_KEY }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
